// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyChU6zChJFQwciOFVPA39rH7TU4e0cQjvA",
    appId: "1:390075232477:android:e2af6db5a13869106b2b34",
    messagingSenderId: "390075232477",
    projectId: "residat-7f3e3",
    androidClientId: "754693177402-591j5gue73i5mm7u80r3rd5jrh2scmvj.apps.googleusercontent.com",
    storageBucket: "residat-7f3e3.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyChU6zChJFQwciOFVPA39rH7TU4e0cQjvA",
    appId: "1:390075232477:android:e2af6db5a13869106b2b34",
    messagingSenderId: "390075232477",
    projectId: "residat-7f3e3",
    storageBucket: "residat-7f3e3.appspot.com",
    iosClientId: '739267820418-ego0tsnaktg58eca2o74m3gqiv5sbt8c.apps.googleusercontent.com',
    iosBundleId: 'com.mapnrank.app',
  );
}
